name: Update Casks

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "15 15 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: ./update-casks.ts
        env:
          GH_TOKEN: ${{ github.token }}
          HIKARI_UPLOAD: ${{ secrets.HIKARI_UPLOAD }}
      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add Casks/
          git commit -m '[CI] Update Casks' || exit 0
          git push
